/*
 * Massachusetts Traffic Rules — reference data.
 *
 * Sourced from the Massachusetts Driver's Manual (RMV), Massachusetts General
 * Laws (M.G.L.) Chapter 89 & 90, and 720 CMR. This is an educational summary,
 * not legal advice. Always verify against the current official manual at
 * https://www.mass.gov/rmv and the General Laws at https://malegislature.gov.
 */

const RULES = [
  {
    id: "speed-limits",
    category: "Speed Limits",
    icon: "🚦",
    title: "Default (statutory) speed limits",
    summary:
      "Unless a posted sign says otherwise, these are the prima facie speed limits in Massachusetts.",
    details: [
      "20 mph in a designated thickly settled or business district (a 'safety zone').",
      "30 mph in a thickly settled or business district (areas with closely spaced homes/buildings).",
      "40 mph outside a thickly settled or business district for at least 1/8 mile.",
      "50 mph on divided highways outside thickly settled areas.",
      "65 mph maximum on most interstate highways where posted.",
      "Exceeding these limits is prima facie evidence of a violation; you must always drive at a 'reasonable and proper' speed for conditions (M.G.L. c. 90 §17).",
    ],
    reference: "M.G.L. c. 90 §17, §18",
    tags: ["speed", "mph", "thickly settled", "highway", "limit"],
  },
  {
    id: "speed-special-zones",
    category: "Speed Limits",
    icon: "🏫",
    title: "School zones & work zones",
    summary: "Reduced limits apply in school and construction zones.",
    details: [
      "School zones are commonly posted at 20 mph when children are present or during posted hours.",
      "Fines are doubled in work zones and school zones.",
      "Slow down and watch for flashing beacons and crossing guards.",
      "Always obey the speed displayed by an active electronic sign.",
    ],
    reference: "M.G.L. c. 90 §17, §18B",
    tags: ["school", "work zone", "construction", "double fine", "children"],
  },
  {
    id: "oui-dui",
    category: "Impaired Driving",
    icon: "🍺",
    title: "OUI — Operating Under the Influence",
    summary:
      "Massachusetts calls drunk/drugged driving 'OUI'. The legal BAC limit is 0.08%.",
    details: [
      "It is illegal to operate with a blood alcohol concentration (BAC) of 0.08% or higher (0.04% for commercial drivers, 0.02% for drivers under 21).",
      "Implied Consent: by driving in MA you consent to a breath/blood test. Refusing triggers an automatic license suspension (180 days for a first offense; longer for repeat offenders or if under 21).",
      "First offense penalties can include up to 2.5 years in jail, fines of $500–$5,000, and a 1-year license suspension.",
      "Massachusetts has a 'Melanie's Law' lookback — prior OUI convictions sharply increase penalties.",
      "An Ignition Interlock Device (IID) is required for repeat offenders and for hardship licenses.",
      "OUI also applies to drugs, including marijuana and prescription medication.",
    ],
    reference: "M.G.L. c. 90 §24, §24D (Melanie's Law)",
    tags: ["oui", "dui", "drunk", "bac", "alcohol", "interlock", "implied consent", "0.08"],
  },
  {
    id: "distracted-driving",
    category: "Distracted Driving",
    icon: "📱",
    title: "Hands-Free Law",
    summary:
      "Since February 2020, drivers may not hold or support any electronic device.",
    details: [
      "You may not hold a phone or electronic device while driving — hands-free mode only.",
      "Activating hands-free mode is allowed only with a single tap or swipe.",
      "Drivers under 18 (junior operators) may NOT use any electronic device at all, even hands-free.",
      "Texting while driving is prohibited for ALL drivers.",
      "Penalties: $100 first offense, $250 second, $500+ and an insurance surcharge for third and subsequent offenses.",
      "Exception: you may use a device to report an emergency.",
    ],
    reference: "M.G.L. c. 90 §13B",
    tags: ["phone", "texting", "hands-free", "distracted", "cell", "device"],
  },
  {
    id: "seatbelts",
    category: "Occupant Safety",
    icon: "🔒",
    title: "Seat belt & child restraint law",
    summary: "All occupants must be properly restrained.",
    details: [
      "Every driver and passenger must wear a safety belt.",
      "Children under 8 years old must be in a federally approved child passenger restraint (car seat or booster), properly fastened.",
      "Children must ride in a car seat/booster until they are 8 years old OR taller than 4 feet 9 inches.",
      "Massachusetts seat belt law is a secondary offense for adults (you can be cited only if stopped for another reason), but the child restraint law is a primary offense.",
      "Fine: $25 for an unbelted adult; $25 per improperly restrained child.",
    ],
    reference: "M.G.L. c. 90 §7AA, §13A",
    tags: ["seatbelt", "seat belt", "car seat", "booster", "child", "restraint"],
  },
  {
    id: "right-of-way",
    category: "Right of Way",
    icon: "🔀",
    title: "Right-of-way & yielding",
    summary: "Who goes first at intersections, rotaries, and crossings.",
    details: [
      "At a 4-way stop, the vehicle that arrives first proceeds first; if two arrive together, the driver on the right has the right of way.",
      "Rotaries/roundabouts: vehicles ALREADY in the rotary have the right of way; yield before entering.",
      "Always yield to pedestrians in a crosswalk — this is the law.",
      "Yield to emergency vehicles with lights/sirens: pull to the right and stop.",
      "When turning left, yield to oncoming traffic.",
      "Yield to a vehicle already in the intersection.",
    ],
    reference: "M.G.L. c. 89 §8, §11",
    tags: ["right of way", "yield", "rotary", "roundabout", "intersection", "4-way"],
  },
  {
    id: "move-over",
    category: "Right of Way",
    icon: "🚨",
    title: "Move Over Law",
    summary: "Give space to stopped emergency and service vehicles.",
    details: [
      "When approaching a stationary emergency, maintenance, or recovery vehicle displaying flashing lights, you must move over one lane if it is safe to do so.",
      "If you cannot move over safely, slow down to a reasonable and safe speed.",
      "Applies to police, fire, ambulances, tow trucks, and highway maintenance vehicles.",
    ],
    reference: "M.G.L. c. 89 §7C",
    tags: ["move over", "emergency", "tow truck", "police", "flashing lights"],
  },
  {
    id: "turn-on-red",
    category: "Traffic Signals",
    icon: "🚥",
    title: "Right turn on red & signals",
    summary: "Rules for turning and obeying signals.",
    details: [
      "Right turn on red is allowed after a complete stop, unless a sign prohibits it (e.g., 'No Turn on Red').",
      "You must yield to pedestrians and cross traffic before turning on red.",
      "Left turn on red is permitted only from a one-way street onto another one-way street, after stopping.",
      "A flashing red light means STOP, then proceed when safe (treat as a stop sign).",
      "A flashing yellow light means slow down and proceed with caution.",
      "A solid yellow light means the signal is about to turn red — stop if you can do so safely.",
    ],
    reference: "M.G.L. c. 89 §8; 720 CMR 9.06",
    tags: ["red light", "turn on red", "signal", "flashing", "yellow", "stop"],
  },
  {
    id: "parking",
    category: "Parking",
    icon: "🅿️",
    title: "Where you may not park",
    summary: "Common no-parking zones across Massachusetts.",
    details: [
      "Within 10 feet of a fire hydrant.",
      "In front of a driveway or in a way that blocks it.",
      "On a crosswalk or sidewalk.",
      "Within 20 feet of an intersection or a stop sign.",
      "Within 20 feet of a fire station driveway (on the same side).",
      "In a bus stop, bike lane, or marked travel lane.",
      "In a space reserved for persons with disabilities without a valid placard/plate (fines start around $100–$300).",
      "Double parking is prohibited.",
    ],
    reference: "M.G.L. c. 90 §18; local ordinances",
    tags: ["parking", "hydrant", "crosswalk", "handicap", "disabled", "no parking"],
  },
  {
    id: "passing",
    category: "Lane Use",
    icon: "↔️",
    title: "Passing & lane discipline",
    summary: "How to pass safely and use lanes correctly.",
    details: [
      "Pass on the left; passing on the right is allowed only in limited situations (e.g., the vehicle ahead is turning left, or on a road wide enough for two lanes in your direction).",
      "Do not cross a solid yellow line on your side to pass.",
      "Keep right except to pass on multi-lane highways.",
      "Use your directional signal before changing lanes or passing.",
      "Return to your lane only when you can see the passed vehicle in your rear-view mirror.",
      "Never exceed the speed limit to pass.",
    ],
    reference: "M.G.L. c. 89 §2, §4, §4B",
    tags: ["passing", "overtake", "lane", "keep right", "double yellow"],
  },
  {
    id: "school-bus",
    category: "Right of Way",
    icon: "🚌",
    title: "Stopping for school buses",
    summary: "You must stop for a school bus with flashing red lights.",
    details: [
      "When a school bus displays flashing red lights and an extended stop sign, you must stop — from BOTH directions.",
      "On a divided highway with a physical median, traffic on the opposite side does not need to stop.",
      "Remain stopped until the red lights stop flashing and the stop sign is withdrawn.",
      "Penalty: $250 fine for a first offense, with escalating penalties and possible license suspension for repeat offenses.",
    ],
    reference: "M.G.L. c. 90 §14",
    tags: ["school bus", "flashing red", "stop sign", "children", "bus"],
  },
  {
    id: "bicycles-pedestrians",
    category: "Vulnerable Users",
    icon: "🚲",
    title: "Bicycles & pedestrians",
    summary: "Sharing the road with people walking and biking.",
    details: [
      "Cyclists have the same rights and duties as motorists and may use the full lane.",
      "When passing a cyclist, leave a safe distance (at least 4 feet is recommended; new rules require a 'safe passing distance').",
      "You may cross a double yellow line to pass a cyclist when it is safe and there is no oncoming traffic.",
      "Stop for pedestrians in any marked crosswalk.",
      "Do not pass a vehicle that has stopped for a pedestrian at a crosswalk.",
      "Yield to a pedestrian using a white cane or guide dog at all times.",
    ],
    reference: "M.G.L. c. 89 §2, §11; c. 90 §14",
    tags: ["bicycle", "cyclist", "pedestrian", "crosswalk", "4 feet", "safe passing"],
  },
  {
    id: "headlights",
    category: "Vehicle Operation",
    icon: "💡",
    title: "Headlights & wipers law",
    summary: "When your headlights must be on.",
    details: [
      "Headlights must be on from 30 minutes after sunset to 30 minutes before sunrise.",
      "Headlights are required during any condition with reduced visibility (under 500 feet).",
      "Massachusetts 'Wipers On, Lights On' rule: if you need your windshield wipers due to weather, your headlights must also be on.",
      "Use low beams within 200 feet of an oncoming vehicle and 300 feet when following another vehicle.",
    ],
    reference: "M.G.L. c. 85 §15; c. 90 §7",
    tags: ["headlights", "lights", "wipers", "high beam", "low beam", "night"],
  },
  {
    id: "junior-operator",
    category: "Licensing",
    icon: "🔰",
    title: "Junior Operator License (under 18)",
    summary: "Stricter rules apply to drivers under 18.",
    details: [
      "For the first 6 months, a junior operator may NOT drive with passengers under 18 (except immediate family) unless a licensed driver 21+ with 1+ year of experience is present.",
      "Junior operators may not drive between 12:30 a.m. and 5:00 a.m. unless accompanied by a parent or legal guardian.",
      "No use of any mobile/electronic device, even hands-free.",
      "Speeding and other violations carry license suspension plus mandatory driver attitudinal retraining.",
      "A learner's permit holder must always be accompanied by a licensed driver 21+ in the front seat.",
    ],
    reference: "M.G.L. c. 90 §8, §8B",
    tags: ["junior", "teen", "under 18", "permit", "curfew", "passenger"],
  },
  {
    id: "registration-insurance",
    category: "Licensing",
    icon: "📄",
    title: "Registration & insurance",
    summary: "Required documents and minimum coverage.",
    details: [
      "All vehicles must be registered with the RMV and display valid plates and a registration sticker.",
      "Massachusetts requires compulsory insurance: minimum 20/40/5 (bodily injury $20k/person, $40k/accident, $5k property damage) plus PIP and uninsured motorist coverage.",
      "Vehicles must pass an annual safety and emissions inspection (look for the inspection sticker on the windshield).",
      "Carry your license, registration, and proof of insurance while driving.",
      "Driving with a suspended/revoked license or without insurance carries heavy fines and possible jail.",
    ],
    reference: "M.G.L. c. 90 §1A, §34A; c. 175",
    tags: ["registration", "insurance", "inspection", "plates", "rmv", "sticker"],
  },
  {
    id: "winter-driving",
    category: "Conditions",
    icon: "❄️",
    title: "Winter & adverse weather driving",
    summary: "Massachusetts winters demand extra caution.",
    details: [
      "Clear all snow and ice from your windows, mirrors, lights, AND roof before driving — flying snow/ice can cause a citation.",
      "Reduce speed and increase following distance on snow, ice, or wet roads.",
      "Bridges and overpasses freeze first.",
      "If you skid, steer gently in the direction you want the front of the car to go; avoid slamming the brakes.",
      "Black ice is most common at dawn, dusk, and on shaded roads.",
    ],
    reference: "M.G.L. c. 90 §17 (reasonable speed); RMV Manual",
    tags: ["winter", "snow", "ice", "weather", "skid", "black ice"],
  },
];

const QUIZ = [
  {
    q: "What is the legal BAC limit for drivers 21 and over in Massachusetts?",
    options: ["0.05%", "0.08%", "0.10%", "0.02%"],
    answer: 1,
    explain: "The legal limit is 0.08% BAC for drivers 21+ (0.02% if under 21).",
  },
  {
    q: "Under the Hands-Free Law, when may you touch your phone while driving?",
    options: [
      "Never, under any circumstance",
      "Only a single tap or swipe to activate hands-free mode",
      "Whenever you are stopped at a red light",
      "Any time as long as you are not texting",
    ],
    answer: 1,
    explain:
      "You may give a single tap or swipe to activate hands-free mode. Holding the device is illegal.",
  },
  {
    q: "Until what age (or height) must a child use a car seat or booster in MA?",
    options: [
      "Age 5 or 3'6\"",
      "Age 6 or 4'0\"",
      "Age 8 or 4'9\"",
      "Age 10 or 5'0\"",
    ],
    answer: 2,
    explain: "Children must be restrained until age 8 OR taller than 4 feet 9 inches.",
  },
  {
    q: "At a rotary (roundabout), who has the right of way?",
    options: [
      "Vehicles entering the rotary",
      "Vehicles already in the rotary",
      "The larger vehicle",
      "Whoever signals first",
    ],
    answer: 1,
    explain: "Vehicles already in the rotary have the right of way; yield before entering.",
  },
  {
    q: "When must you stop for a school bus?",
    options: [
      "Only if you are directly behind it",
      "When its red lights flash, from both directions (unless a median divides the road)",
      "Only on local roads",
      "Never, just slow down",
    ],
    answer: 1,
    explain:
      "Stop from both directions when red lights flash, unless a physical median separates opposing traffic.",
  },
  {
    q: "What is the default speed limit in a thickly settled or business district?",
    options: ["20 mph", "30 mph", "40 mph", "50 mph"],
    answer: 1,
    explain: "30 mph is the statutory limit in a thickly settled or business district unless posted otherwise.",
  },
  {
    q: "Under the 'Wipers On' rule, what else must be on?",
    options: ["Hazard lights", "Headlights", "Fog lights only", "Nothing"],
    answer: 1,
    explain: "If weather requires your wipers, your headlights must also be on.",
  },
  {
    q: "A left turn on a red light is allowed only when...",
    options: [
      "Turning from a one-way street onto another one-way street, after stopping",
      "Never",
      "There is no oncoming traffic",
      "On any road after 9 p.m.",
    ],
    answer: 0,
    explain: "Left on red is permitted only from a one-way onto another one-way street, after a full stop.",
  },
  {
    q: "How far from a fire hydrant must you park?",
    options: ["5 feet", "10 feet", "15 feet", "25 feet"],
    answer: 1,
    explain: "You must park at least 10 feet away from a fire hydrant.",
  },
  {
    q: "Refusing a breath test (Implied Consent) on a first offense results in...",
    options: [
      "A warning",
      "A 180-day license suspension",
      "A $50 fine only",
      "No penalty",
    ],
    answer: 1,
    explain: "Refusal triggers an automatic 180-day license suspension on a first offense.",
  },
];

if (typeof module !== "undefined") {
  module.exports = { RULES, QUIZ };
}
